# Generated by Django 3.1.7 on 2021-05-13 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0017_articlelikes_commentlikes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlelikes',
            options={'verbose_name': 'Лайк статьи', 'verbose_name_plural': 'Лайки статей'},
        ),
        migrations.AlterModelOptions(
            name='commentlikes',
            options={'verbose_name': 'Лайк комментария', 'verbose_name_plural': 'Лайки комментариев'},
        ),
        migrations.AlterModelTable(
            name='articlelikes',
            table='article_likes',
        ),
        migrations.AlterModelTable(
            name='commentlikes',
            table='comment_likes',
        ),
    ]
